admin:
  email: admin@myblog.example.com
  username: admin
affinity: {}
database:
  internal: true
  type: internal
fullnameOverride: my-wordpress-site
image:
  pullPolicy: IfNotPresent
  repository: wordpress
  tag: latest
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  className: nginx
  enabled: true
  hosts:
  - host: myblog.example.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - myblog.example.com
    secretName: my-wordpress-site-tls
nameOverride: my-wordpress-site
nodeSelector: {}
persistence:
  enabled: true
  size: 5Gi
  storageClass: gp2
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi
service:
  port: 80
  type: ClusterIP
tolerations: []
