version: "3.8"

services:
  backend:
    image: website-idp-backend:latest
    container_name: idp-backend-test
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITHUB_REPO=apps-repo
      - GITHUB_OWNER=NaserRaoofi
    volumes:
      - backend_data:/app/website-template/values
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - idp-network

  frontend:
    image: website-idp-frontend:latest
    container_name: idp-frontend-test
    ports:
      - "3001:8080"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - idp-network

volumes:
  backend_data:

networks:
  idp-network:
    driver: bridge
