apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website-template.fullname" . }}
  labels:
    {{- include "website-template.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "website-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "website-template.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            # Website Type Specific Environment Variables
            {{- if eq .Values.image.repository "wordpress" }}
            - name: WORDPRESS_DB_HOST
              value: {{ include "website-template.databaseHost" . }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.admin.username }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "website-template.fullname" . }}-secrets
                  key: admin-password
            - name: WORDPRESS_DB_NAME
              value: {{ include "website-template.databaseName" . }}
            {{- else if eq .Values.image.repository "drupal" }}
            - name: DRUPAL_DATABASE_HOST
              value: {{ include "website-template.databaseHost" . }}
            - name: DRUPAL_DATABASE_USER
              value: {{ .Values.admin.username }}
            - name: DRUPAL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "website-template.fullname" . }}-secrets
                  key: admin-password
            - name: DRUPAL_DATABASE_NAME
              value: {{ include "website-template.databaseName" . }}
            {{- end }}
            # Custom environment variables
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: website-storage
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: website-storage
          persistentVolumeClaim:
            claimName: {{ include "website-template.fullname" . }}-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
